module.exports = {
    MAX_REPO_FILES: 2000,
    MAX_REPO_SIZE_MB: 50,
    MAX_TIER1_FILES: 30,
    MAX_TIER2_FILES: 50,
    RATE_LIMIT_THRESHOLD: 50,
    CACHE_TTL_HOURS: 24,
    CLAUDE_MAX_RETRIES: 3,
    CLAUDE_CONCURRENCY: 3,
    MAX_DOC_FAILURES: 4,
  };
